### ISSUE TITLE
Suggestion on wordbook words store format

### ISSUE THREAD

**Issue by pannz** [wordway/wordway-app#9]
Since the word book use yaml to collection and organize the words, and the words are stored by following:

```
words:
  -
    word: hello
  -
    word: world


...
```

Not sure you have consider this, my personal thought, it would be better if we can support for this kind of format:

```
worlds:
   hello: meaning of this world, can use self explain
   awesome:       # empty, in app, it automatically use youdao dict

...
```
or if we make it more flexible

```
words:
   word:
       meaning:  the meaning of this word
       tag:  the category might be useful
       ...
   anotherwold:

...
```

In this way, its easy for other scripts to read and write it and avoid the duplication of words.
Current the words are store as like a List/Array, it not friendly for de-duplication when someone  use scripts to read and write, when combine workflows or others to enrich personal wordbook in daily work or life.

**Comment by lijy91** [comment]
你提出的建议我在设计的时候有考虑过

第1种在需要有其他字段来描述该单词时将不可用
第2种在仅添加单词（key）时而不添加任何其他字段来描述的时候将不可以，或者会导致格式很奇怪

如果使用 json 描述将会是这样，anotherwold 不需要任何其他字段（由后台获取其他信息），需要加一个空对象在后面或者空字符

```json
{
  "word": {
    "meaning": "",
   "tag": ""
  },
  "anotherwold": {}
}
```

这是两种情况混用的现行方式
```yaml
  - word: maven
  - word: Microsoft
  - word: module
  - custom: true
    word: nginx
    remark: Nginx（发音同engine x）是异步框架的网页服务器，也可以用作反向代理、负载平衡器和HTTP缓存。
    us_ipa: ˌɛndʒɪnˈɛks
    us_pronunciation_url: assets/en-us-nginx.mp3
  - word: "null"
  - custom: true
    word: "OS X"
    remark: 苹果公司推出的基于图形用户界面操作系统，为麦金塔的主操作系统。
    us_pronunciation_url: assets/en-us-osx.mp3
```
